### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by rodolfoplondero** [rodolfoplondero/rodolfoplondero#1]
![Matlab](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2F2%2F21%2FMatlab_Logo.png&f=1&nofb=1)

**Comment by RodLondero** [comment]
![Layer1023](https://user-images.githubusercontent.com/4026108/115160975-63243d00-a071-11eb-8392-28fffe3045a2.png)
